---
- name: display hostname, domain name and nameservers
  hosts: nxos
  connection: local
  gather_facts: no
  vars:
    includes:
      - hostname
      - domain-lookup
      - name-server

  tasks:

  - name: run the commands
    ios_command:
      commands:
      - sh run | include {{ item }}
    loop: "{{ includes }}"
    register: result

  - debug:
      var: item.stdout
    loop: "{{ result.results }}"
