---
- name: base configuration
  hosts: nxos
  connection: local
  gather_facts: no
  
  tasks:
  - name: set hostnames
    cisco.nxos.nxos_system:
      hostname: "{{ inventory_hostname }}"

  - name: no switchport
    nxos_config:
      lines:
        - config t
        - interface Ethernet1/1 - 3
        - no switchport

  - name: configure loopbacks
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: '{{ item.interface }}'
        ipv4:
        - address: "{{ item.addr }}"
      state: replaced
    with_items: "{{ loopback_interfaces }}"

  - name: configure switchports
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: '{{ item.interface }}'
        ipv4:
        - address: "{{ item.addr }}"
      state: replaced
    with_items: "{{ ethernet_interfaces }}"

  - name: open switchports
    nxos_config:
      lines:
        - config t
        - interface Ethernet1/1 - 3
        - no shutdown