---
- name: show version
  hosts: nxos
  connection: local
  gather_facts: no
  
  tasks:
    - name: Execute single "show version" command.
      cisco.nxos.nxos_command:
        commands: "show version"
      register: response

    - name: Print the command output
      debug:
        var: response.stdout
